---

- name: Install gsettings packages
  apt:
    name: libglib2.0-bin
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - gsettings

- name: Set gsettings per user
  command: "gsettings set {{item.1.schema}} {{item.1.key}} {{item.1.value}}"
  become: yes
  become_user: "{{item.0.user}}"
  with_subelements:
    - "{{gsettings_per_user}}"
    - gsettings
  when: ansible_os_family == 'Debian'
  tags:
    - gsettings

- name: Copy gsettings-dump to /usr/local/bin
  copy:
    src: gsettings-dump
    dest: /usr/local/bin/gsettings-dump
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'
  tags:
    - gsettings
