---

- name: Install gsettings packages
  apt:
    name: libglib2.0-bin
    state: present
  when: ansible_os_family == 'Debian'
  tags:
    - gsettings

- name: Set gsettings settings for user
  command: "gsettings set {{item.schema}} {{item.key}} {{item.value}}"
  become: yes
  become_user: "{{gsettings_user}}"
  with_items: "{{gsettings_settings}}"
  when: ansible_os_family == 'Debian'
  tags:
    - gsettings

- name: Copy gsettings-dump to /usr/local/bin
  copy:
    src: gsettings-dump
    dest: /usr/local/bin/gsettings-dump
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'
  tags:
    - gsettings
